name: Profiler
version: "2.1.3"
description: Allows user to update or delete their profile
url: https://statamic.com/marketplace/addons/profiler
developer: Erin Dalzell
developer_url: silentzconsulting.com
commercial: true