name: Profiler
version: "2.0.2"
description: Allows user to update their profile
url: https://statamic.com/marketplace/addons/profiler
developer: Erin Dalzell
developer_url: silentzconsulting.com
commercial: true